name: elephant_vpn
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  # Getx for state management
  get: ^4.6.5

  # Cupertino style icons
  cupertino_icons: ^1.0.2

  # For API Call
  http: ^1.0.0

  # Converting CSV data to List
  csv: ^5.0.2

  # For Lottie Animation
  lottie: ^2.3.2

  # For storing data (in local storage) 
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For integrating ads
  google_mobile_ads: ^3.0.0

  # For firebase
  firebase_core: ^2.14.0

  # For Remote Config
  firebase_remote_config: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.1.0

  # For icons_launcher:
  flutter_launcher_icons: "^0.13.1"

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo.png"